//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 BottleDetMain.rc 使用
//
#define ID_Confirm                      2
#define ID_Activate                     3
#define ID_show                         4
#define ID_Back                         5
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BOTTLEDETMAIN_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDD_CHECK_PARAM_DIALOG          130
#define IDD_CAMERA_PARAM_DIALOG         132
#define IDD_CHANGE_CLASS_DIALOG         134
#define IDD_SYSTEM_PARAM_DIALOG         136
#define IDD_LOGIN_DIALOG                138
#define IDD_BEGIN_DIALOG                143
#define IDD_STAT_DLG                    145
#define IDD_STATE_DLG                   145
#define IDD_EDIT_PASS_DLG               146
#define IDD_MOLD_SELECT_DIALOG          148
#define IDB_DET_PARAOFF                 152
#define IDB_DET_PARAON                  153
#define IDB_UNLOCKOFF                   154
#define IDB_UNLOCKON                    155
#define IDB_ZEROOFF                     156
#define IDB_ZEROON                      157
#define IDB_LOCKOFF                     158
#define IDB_LOCKON                      159
#define IDB_STOPOFF                     160
#define IDB_STOPON                      161
#define IDB_EXITOFF                     162
#define IDB_EXITON                      163
#define IDB_SYS_PARAOFF                 164
#define IDB_SYS_PARAON                  165
#define IDB_CAM_PARAOFF                 166
#define IDB_CAM_PARAON                  167
#define IDB_AUTO_DETOFF                 168
#define IDB_AUTO_DETON                  169
#define IDB_CHANGECLASS_ON              171
#define IDB_STATE_OFF                   172
#define IDB_STATE_ON                    173
#define IDB_BITMAP1                     174
#define IDB_CHANGECLASS_OFF             174
#define IDD_MOLD_PARAM_DIALOG           175
#define IDD_REGIST_DLG                  177
#define IDD_Change_DIALOG               179
#define IDD_admin_management            181
#define IDC_BUT_AUTO_DET                1000
#define IDC_BUT_LOCK                    1001
#define IDC_BUT_DET_PARAM               1002
#define IDC_BUT_CAM_PARAM               1003
#define IDC_BUT_CHANGE_CLASS            1004
#define IDC_BUT_SYSTEM_PARAM            1005
#define IDC_BUT_STAT                    1006
#define IDC_BUT_EXIT                    1007
#define IDC_BUT_User_Management         1008
#define IDC_BUT_CLEAR                   1009
#define IDC_LIST_BAD_BOTTLE             1010
#define IDC_IMAGE_WIN                   1011
#define IDC_CLASS_BOX                   1012
#define IDC_SPEED_BOX                   1013
#define IDC_RUN_TIME_BOX                1014
#define IDC_LOCAL_TIME_BOX              1015
#define IDC_DET_TIME_BOX                1016
#define IDC_NUM_TOTAL                   1017
#define IDC_NUM_BAD                     1018
#define IDC_NUM_BAD_RATIO               1019
#define IDC_TOTAL                       1020
#define IDC_MAKING_NUMBER               1020
#define IDC_BAD                         1021
#define IDC_DEADLINE                    1021
#define IDC_BAD_RATIO                   1022
#define IDC_DOWN_READ_NUMBER            1022
#define IDC_SYSTEEM_BOX                 1023
#define IDC_DET_BOX                     1024
#define IDC_BAD_BOTTLE_BOX              1025
#define IDC_NUM_BAD_RATIO2              1026
#define IDC_DOWN_READ_CODE              1027
#define IDC_BUT_LOAD_MODEL              1028
#define IDC_BUT_LOAD_PARAM_FILE         1029
#define IDC_BUT_LOAD_IMAGE              1030
#define IDC_BUT_RUN_TEST                1031
#define IDC_RADIO_SHOW_REGION           1032
#define IDC_BUT_SAVE_PARAM              1033
#define IDC_TEST_IMAGE_WIN              1035
#define IDC_MODEL_BOX                   1036
#define IDC_PARAM_FILE_BOX              1037
#define IDC_MODEL_LABEL                 1038
#define IDC_PARAM_FILE_LABEL            1039
#define IDC_DET_PARAM_BOX               1040
#define IDC_OPERATE_BOX                 1041
#define IDC_OPEN_IMAGE_LABEL            1042
#define IDC_IMAGE_PATH_BOX              1043
#define IDC_EDIT_DET_THRE               1044
#define IDC_DETTHRE_LABEL               1045
#define IDC_EDIT_EXPOSE_TIME            1046
#define IDC_EDIT_GAIN                   1047
#define IDC_IMAGE_IDC_EDIT_TESTDEADLINE 1047
#define IDC_BUT_SAVE_CAM_PARAM          1048
#define IDC_UPREAD_NUMBER               1048
#define IDC_BUT_EXIT_CAM_PARAM          1049
#define IDC_TEST_UPREAD_MOLD            1049
#define IDC_BUT_GRAY_SINGLE             1050
#define IDC_TEST_DOWNREAD_MOLD          1050
#define IDC_BUT_GRAY_STILL              1051
#define IDC_DOWNREAD_NUMBER             1051
#define IDC_AUTO_SAVE                   1052
#define IDC_TEST_UPRESULT               1052
#define IDC_TEST_UPRESULT2              1053
#define IDC_TEST_DOWNRESULT             1053
#define IDC_BUT_CONNECTION_TEST         1054
#define IDC_BUT_DISCONNEXTION           1055
#define IDC_CAM_IMAGE_WIN               1056
#define IDC_CAMERA_PARAM_BOX            1057
#define IDC_CAMERA_TEST_BOX             1058
#define IDC_EXPOSR_TIME_LABEL           1059
#define IDC_GAIN_LABEL                  1060
#define IDC_BUT_EXIT_DET_PARAM          1061
#define IDC_EXPOSE_L                    1062
#define IDC_CLASS_LIST                  1064
#define IDC_BUT_SELECT                  1066
#define IDC_BUT_DELETE                  1067
#define IDC_BUT_RENAME                  1068
#define IDC_BUT_CREATE                  1069
#define IDC_EDIT_CLASS_NAME             1070
#define IDC_BUT_CERTAIN_NAME            1071
#define IDC_CHANGE_LABEL                1072
#define IDC_RADIO_THROW_NORMAL          1073
#define IDC_RADIO_THROW_STILL           1074
#define IDC_RADIO_THROW_NO              1075
#define IDC_RADIO_SHOW_STILL            1076
#define IDC_RADIO_SHOW_BAD              1077
#define IDC_RADIO_SAVE_AUTO_OFF         1078
#define IDC_RADIO_SAVE_AUTO_ON          1079
#define IDC_RADIO_SAVE_AUTO_BAD         1080
#define IDC_COMBO_IMG_FORM              1081
#define IDC_CHECK_AUTO_LOCK             1086
#define IDC_EDIT_AUTO_LOCK_TIME         1087
#define IDC_BUT_CERTION_SYSTEM_PARAM    1088
#define IDC_BUT_EXIT_SYSTEM_PARAM       1089
#define IDC_THROW_MODEL_BOX             1090
#define IDC_BAD_SHOW_BOX                1091
#define IDC_SAVE_IMAGE_BOX              1092
#define IDC_IMG_FORM                    1093
#define IDC_EDIT_NAME                   1094
#define IDC_EDIT_USERNAME               1094
#define IDC_EDIT_PASSWORD               1095
#define IDC_Login_PASSWORD              1095
#define IDC_LOGIN                       1096
#define IDC_BTN_LOGIN                   1096
#define IDC_EDIT_PASSWORD2              1097
#define IDC_EDIT2                       1098
#define IDC_CHECK_SHOW                  1098
#define IDC_EDIT_GRABNUM                1098
#define IDC_EDIT_RIGHT_VAL              1098
#define IDC_EDIT1                       1099
#define IDC_CHECK1                      1099
#define IDC_CHECK_AUTO_SAVE             1099
#define IDC_EDIT_WRITE_PASSWORD         1099
#define IDC_CHECK_AREA_THRESH           1099
#define IDC_CHECK_MOLDRECOGNIZE         1099
#define IDC_EDIT_LEFT_VAL               1099
#define IDC_EDIT_PRODUCT_BATCH          1099
#define IDC_CHECK_REIGSTSHOW            1099
#define IDC_password                    1099
#define IDC_BUTTON1                     1100
#define IDC_CHECK_TRIGER                1100
#define IDC_BUT_CHANGE_CLASS_DET        1100
#define IDC_BUT_CHANGE_PASSWORD         1100
#define IDC_BUT_INQUIRE                 1100
#define IDC_BUT_MOLD1                   1100
#define IDC_BUT_PINGDI                  1100
#define IDC_OK                          1100
#define IDC_password2                   1100
#define IDC_TIP                         1101
#define IDC_BOTTLE_DET_CLASS            1101
#define IDC_TIPP                        1101
#define IDC_BUT_MOLD2                   1101
#define IDC_REGIST_PASSWORD             1101
#define IDC_BTN_LOGIN3                  1101
#define IDC_BOTTLE_DET_CLASS_BOX        1102
#define IDC_BUT_MOLD3                   1102
#define IDC_CONFIRM_PASSWORD            1102
#define IDC_BTN_LOGIN4                  1102
#define IDC_BTN_Changepassword          1102
#define IDC_MFCCOLORBUTTON1             1103
#define IDC_BUT_MOLD4                   1103
#define IDC_EDIT_IDCODE                 1103
#define IDC_STAT_PAINT_CONTROL          1104
#define IDC_BUT_MOLD5                   1104
#define IDC_BTN_Back                    1104
#define IDOK_PASSWORLD                  1105
#define IDC_BUT_MOLD6                   1105
#define IDC_Username                    1105
#define IDCANCEL_PASSWORD               1106
#define IDC_BUT_MOLD7                   1106
#define IDC_BTN_Regist                  1106
#define IDC_STATIC_COM_PASS             1107
#define IDC_BUT_MOLD8                   1107
#define IDC_STATIC_USERNAME             1108
#define IDC_BUT_MOLD9                   1108
#define IDC_STATIC_USER_PASS            1109
#define IDC_BUT_MOLD10                  1109
#define IDC_STATE_PISTURE               1110
#define IDC_BUT_MOLD11                  1110
#define IDC_STATIC_USERNAME2            1110
#define IDC_MONTHCALENDAR_TIME          1111
#define IDC_BUT_MOLD12                  1111
#define IDC_STATIC_COM_PASS2            1111
#define IDC_CUSTOM_CHART                1112
#define IDC_BUT_MOLD13                  1112
#define IDC_STATIC_USERNAME3            1112
#define IDC_GROUP_STAT_PARAM            1113
#define IDC_BUT_MOLD14                  1113
#define IDC_STATIC_REGIST_PASS          1113
#define IDC_TIME_COSTS                  1114
#define IDC_BUT_MOLD15                  1114
#define IDC_STATIC_CONFIRM_PASS         1114
#define IDC_CHECK_LBW_THRESH            1115
#define IDC_BUT_MOLD16                  1115
#define IDC_STATIC_IDCODE               1115
#define IDC_EDIT_LBW_THRESH             1116
#define IDC_BUT_MOLD17                  1116
#define IDC_CHECK_GRAY                  1117
#define IDC_BUT_MOLD18                  1117
#define IDC_EDIT3                       1118
#define IDC_EDIT_GRAY_VALUE             1118
#define IDC_BUT_MOLD19                  1118
#define IDC_CENTER_DET                  1119
#define IDC_BUT_MOLD20                  1119
#define IDC_CHECK_CENTER_AI             1120
#define IDC_BUT_MOLD21                  1120
#define IDC_CHECK_CENTER_TRADITION      1121
#define IDC_BUT_MOLD22                  1121
#define IDC_AREA_DET                    1122
#define IDC_BUT_MOLD23                  1122
#define IDC_CHECK_AREA_AI               1123
#define IDC_BUT_MOLD24                  1123
#define IDC_STATI                       1124
#define IDC_CHOSE_ALGO_BOX              1124
#define IDC_BUT_MOLD25                  1124
#define IDC_BUT_MOLD26                  1125
#define IDC_BUT_MOLD27                  1126
#define IDC_BUT_MOLD28                  1127
#define IDC_BUT_MOLD29                  1128
#define IDC_BUT_MOLD30                  1129
#define IDC_BUT_MOLD31                  1130
#define IDC_BUT_MOLD32                  1131
#define IDC_BUT_MOLD33                  1132
#define IDC_BUT_MOLD34                  1133
#define IDC_BUT_MOLD35                  1134
#define IDC_BUT_MOLD36                  1135
#define IDC_BUT_MOLD37                  1136
#define IDC_BUT_MOLD38                  1137
#define IDC_BUT_MOLD39                  1138
#define IDC_BUT_MOLD40                  1139
#define IDC_BUT_MOLD41                  1140
#define IDC_BUT_MOLD42                  1141
#define IDC_BUT_MOLD43                  1142
#define IDC_BUT_MOLD44                  1143
#define IDC_BUT_MOLD45                  1144
#define IDC_BUT_MOLD46                  1145
#define IDC_BUT_MOLD47                  1146
#define IDC_BUT_MOLD48                  1147
#define IDC_BUT_MOLD49                  1148
#define IDC_BUT_MOLD50                  1149
#define IDC_BUT_MOLD51                  1150
#define IDC_BUT_MOLD52                  1151
#define IDC_BUT_MOLD53                  1152
#define IDC_BUT_MOLD54                  1153
#define IDC_BUT_MOLD55                  1154
#define IDC_BUT_MOLD56                  1155
#define IDC_BUT_MOLD57                  1156
#define IDC_BUT_MOLD58                  1157
#define IDC_BUT_MOLD59                  1158
#define IDC_BUT_MOLD60                  1159
#define IDC_BUT_MOLD61                  1160
#define IDC_BUT_MOLD62                  1161
#define IDC_BUT_MOLD63                  1162
#define IDC_BUT_MOLD64                  1163
#define IDC_BUT_MOLD65                  1164
#define IDC_BUT_MOLD66                  1165
#define IDC_BUT_MOLD67                  1166
#define IDC_BUT_MOLD68                  1167
#define IDC_BUT_MOLD69                  1168
#define IDC_BUT_MOLD70                  1169
#define IDC_BUT_MOLD71                  1170
#define IDC_BUT_MOLD72                  1171
#define IDC_BUT_MOLD73                  1172
#define IDC_BUT_MOLD74                  1173
#define IDC_BUT_MOLD75                  1174
#define IDC_BUT_MOLD76                  1175
#define IDC_BUT_MOLD77                  1176
#define IDC_BUT_MOLD78                  1177
#define IDC_BUT_MOLD79                  1178
#define IDC_BUT_MOLD80                  1179
#define IDC_BUT_MOLD81                  1180
#define IDC_BUT_MOLD82                  1181
#define IDC_BUT_MOLD83                  1182
#define IDC_BUT_MOLD84                  1183
#define IDC_BUT_MOLD85                  1184
#define IDC_BUT_MOLD86                  1185
#define IDC_BUT_MOLD87                  1186
#define IDC_BUT_MOLD88                  1187
#define IDC_BUT_MOLD89                  1188
#define IDC_BUT_MOLD90                  1189
#define IDC_BUT_SELECT_SAVE             1191
#define IDC_BUT_SELECT_EXIT             1193
#define IDC_BUT_MOLD_SELECT             1194
#define IDC_BUT_OUTER_RECTANGLE         1195
#define IDC_BUT_OUTER_POLYGON           1196
#define IDC_BUT_OUTER_CYCLE             1197
#define IDC_BUT_INNER_RECTANGLE         1198
#define IDC_BUT_INNER_POLYGON           1199
#define IDC_BUT_INNER_CYCLE             1200
#define IDC_BUT_DELETE_REGION           1201
#define IDC_BUT_SAVE_REGION             1202
#define IDC_BUT_LOAD_MOLD_MODEL         1203
#define IDC_MOLD_PARAM_FILE_BOX         1204
#define IDC_STATIC_SELECT_MOLD_MODEL    1205
#define IDC_STATIC_SHOW_MOLD_SELECTED   1206
#define IDC_STATIC_SELECT_DONE          1207
#define IDC_MOLD_NUM                    1208
#define IDC_NUM_MOLD                    1208
#define IDC_MOLD                        1209
#define IDC_UP_READ_NUMBER              1209
#define IDC_MOLD_SELECT_BOX             1210
#define IDC_MOLD_DO_BOX                 1211
#define IDC_GRABNUM_LABEL               1212
#define IDC_BUT_LAST                    1213
#define IDC_BUT_NEXT                    1214
#define IDC_STATIC_NUMBER               1215
#define AI                              1216
#define IDC_BUT_AITOOL                  1216
#define IDC_NUM_MOLD_RATIO              1217
#define IDC_ID_RATIO                    1218
#define IDC_UP_READ_CODE                1218
#define IDC_BUTTON2                     1219
#define IDC_BUT_MOLD0                   1219
#define IDC_BUT_GRAB_TEST               1219
#define IDC_BUT_MOHAO                   1219
#define IDC_BUT_MOLD_RUN_TEST           1219
#define IDC_NUM_MOLD_RATIO2             1219
#define IDC_RADIO_MASK1                 1220
#define IDC_NUM_MOLD_RATIO3             1220
#define IDC_RADIO_MASK2                 1221
#define IDC_RADIO_MASK3                 1222
#define IDC_RADIO_MASK4                 1223
#define IDC_BOX_DRAWREGION              1224
#define IDC_CHECK_DUIBI                 1225
#define IDC_EDIT_DUIBI_VALUE            1226
#define IDC_COMBO_IMAGE_NUM             1227
#define IDC_CHECK_CAMERA_OUT            1228
#define IDC_COMBO_PART_NUM              1230
#define IDC_RADIO_ONE                   1231
#define IDC_RADIO_TWO                   1232
#define IDC_RADIO3                      1233
#define IDC_RADIO_THREE                 1233
#define IDC_RADIO_PIC3                  1233
#define IDC_RADIO_PIC1                  1234
#define IDC_RADIO_PIC2                  1235
#define IDC_RADIO_PIC4                  1236
#define IDC_RADIO5                      1237
#define IDC_RADIO_PIC5                  1237
#define IDC_MOLD_IMAGE                  1238
#define IDC_LEFT_VAL                    1239
#define IDC_RIGHT_VAL                   1240
#define IDC_BUT_MOLD_EXIT               1241
#define IDC_BUT_READ_MOLD_IMAGE         1242
#define IDC_BUTTON5                     1243
#define IDC_BUT_MOLD_SAVE               1243
#define IDC_STATIC_UP                   1244
#define IDC_STATIC_DOWN                 1245
#define IDC_BUTTON3                     1246
#define IDC_STATIC_PRODUCT_BATCH        1247
#define IDC_BUTTON4                     1249
#define IDC_EDIT_PhotoelectricDistance  1250
#define IDC_STATIC_PhotoelectricDistance 1251
#define IDC_STATIC_TriggerDistance      1252
#define IDC_EDIT_TriggerDistance        1253
#define IDC_BUTTON                      1254
#define IDC_BUTTON_CullingTest          1254
#define IDC_STATIC_REMOVEBOX            1255
#define IDC_EDIT_TEST_Deadline          1256
#define IDC_STATIC_TESTDeadline         1257
#define IDC_TEST_UP_READ_NUMBER         1258
#define IDC_TEST_UP_READ_MOLD           1259
#define IDC_TEST_DOWN_READ_NUMBER       1260
#define IDC_TEST_DOWN_READ_MOLD         1261
#define IDC_TEST_UP_RESULT              1262
#define IDC_TEST_DOWN_RESULT            1263
#define IDC_Change_PASSWORD             1263
#define IDC_Used_PASSWORD               1264
#define IDC_STATIC_User                 1265
#define IDC_STATIC_UsedPassword         1266
#define IDC_STATIC_NewPassword          1267
#define IDC_STATIC_NewPassword_Confirm  1268
#define IDC_Regist_SHOW                 1268
#define IDC_Change_PASSWORD_Confirm     1269
#define IDC_STATIC_password             1273
#define ID_Lock                         1274
#define IDC_STATIC_password2            1275
#define IDC_LIST                        1278

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        183
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1279
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
