/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 23.11
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef HCPP_HMEMORYBLOCK
#define HCPP_HMEMORYBLOCK

namespace HalconCpp
{

// Represents an instance of a memory block.
class LIntExport HMemoryBlock : public HHandle
{

public:

  // Create an uninitialized instance
  HMemoryBlock():HHandle() {}

  // Copy constructor
  HMemoryBlock(const HMemoryBlock& source) : HHandle(source) {}

#if __cplusplus >= 201103
  // C++11 deprecates declaration of an implicit default assignment operator if
  // the class has a custom copy constructor.
  HMemoryBlock& operator=(const HMemoryBlock&) = default;
#endif

  // Copy constructor
  HMemoryBlock(const HHandle& handle);

  // Create HMemoryBlock from handle, taking ownership
  explicit HMemoryBlock(Hlong handle);

  bool operator==(const HHandle& obj) const
  {
    return HHandleBase::operator==(obj);
  }

  bool operator!=(const HHandle& obj) const
  {
    return HHandleBase::operator!=(obj);
  }

protected:

  // Verify matching semantic type ('memory_block')!
  virtual void AssertType(Hphandle handle) const;

public:



/*****************************************************************************
 * Operator-based class constructors
 *****************************************************************************/

  // create_memory_block_extern: Create a memory block from an external pointer.
  explicit HMemoryBlock(void* Pointer, Hlong Size, void* FreeFunction);

  // create_memory_block_extern_copy: Create a memory block from an external pointer by copying.
  explicit HMemoryBlock(void* Pointer, Hlong Size);

  // read_memory_block: Read a memory block from a file.
  explicit HMemoryBlock(const HString& FileName);

  // read_memory_block: Read a memory block from a file.
  explicit HMemoryBlock(const char* FileName);

#ifdef _WIN32
  // read_memory_block: Read a memory block from a file.
  explicit HMemoryBlock(const wchar_t* FileName);
#endif




  /***************************************************************************
   * Operators                                                               *
   ***************************************************************************/

  // Create a memory block from an external pointer.
  void CreateMemoryBlockExtern(void* Pointer, Hlong Size, void* FreeFunction);

  // Create a memory block from an external pointer by copying.
  void CreateMemoryBlockExternCopy(void* Pointer, Hlong Size);

  // Return the data pointer and size of a memory block.
  void* GetMemoryBlockPtr(Hlong* Size) const;

  // Read a memory block from a file.
  void ReadMemoryBlock(const HString& FileName);

  // Read a memory block from a file.
  void ReadMemoryBlock(const char* FileName);

#ifdef _WIN32
  // Read a memory block from a file.
  void ReadMemoryBlock(const wchar_t* FileName);
#endif

};

// forward declarations and types for internal array implementation

template<class T> class HSmartPtr;
template<class T> class HHandleBaseArrayRef;

typedef HHandleBaseArrayRef<HMemoryBlock> HMemoryBlockArrayRef;
typedef HSmartPtr< HMemoryBlockArrayRef > HMemoryBlockArrayPtr;


// Represents multiple tool instances
class LIntExport HMemoryBlockArray : public HHandleBaseArray
{

public:

  // Create empty array
  HMemoryBlockArray();

  // Create array from native array of tool instances
  HMemoryBlockArray(const HMemoryBlock* classes, Hlong length);

  // Copy constructor
  HMemoryBlockArray(const HMemoryBlockArray &tool_array);

  // Destructor
  virtual ~HMemoryBlockArray();

  // Assignment operator
  HMemoryBlockArray &operator=(const HMemoryBlockArray &tool_array);

  // Clears array and all tool instances
  virtual void Clear();

  // Get array of native tool instances
  const HMemoryBlock* Tools() const;

  // Get number of tools
  virtual Hlong Length() const;

  // Create tool array from tuple of handles
  virtual void SetFromTuple(const HTuple& handles);

  // Get tuple of handles for tool array
  virtual HTuple ConvertToTuple() const;

protected:

// Smart pointer to internal data container
   HMemoryBlockArrayPtr *mArrayPtr;
};

}

#endif
